# Generated by Django 3.2.9 on 2021-11-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_calificaciones_comentarios_pregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificaciones',
            old_name='id_calificacion',
            new_name='id_comprador',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='id_comentario',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='id_pregunta',
        ),
    ]
