# Generated by Django 3.2.9 on 2021-12-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('id_producto', models.IntegerField(default=0)),
                ('id_comprador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(default=0)),
                ('date_comment', models.DateTimeField(verbose_name='Fecha de creacion')),
                ('rate_comment', models.IntegerField()),
                ('comment', models.CharField(default='', max_length=70)),
                ('user', models.CharField(max_length=70)),
                ('email_user', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pregunta', models.DateTimeField(verbose_name='Fecha de creacion')),
                ('pregunta', models.CharField(default='', max_length=70)),
                ('user', models.CharField(max_length=70)),
                ('email_user', models.CharField(max_length=70)),
            ],
        ),
    ]
